In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
routes = pd.read_csv("../chicago_gtfs/routes.txt")

In [4]:
trips = pd.read_csv("../chicago_gtfs/trips.txt")

In [5]:
stop_times = pd.read_csv("../chicago_gtfs/stop_times.txt")

In [6]:
stops = pd.read_csv("../chicago_gtfs/stops.txt")

In [7]:
calendar = pd.read_csv("../chicago_gtfs/calendar.txt")
calendar_dates = pd.read_csv("../chicago_gtfs/calendar_dates.txt")

In [44]:
frequencies = pd.read_csv("../chicago_gtfs/frequencies.txt")

In [46]:
shapes = pd.read_csv("../chicago_gtfs/shapes.txt")

In [9]:
print(routes.head())

   agency_id route_id route_short_name            route_long_name  route_type  \
0      50066        1                1  Bronzeville/Union Station           3
1      50066        2                2          Hyde Park Express           3
2      50066        3                3                 King Drive           3
3      50066        4                4              Cottage Grove           3
4      50066       X4               X4      Cottage Grove Express           3

                               route_url route_color route_text_color
0   http://www.transitchicago.com/bus/1/      99999C           ffffff
1   http://www.transitchicago.com/bus/2/      b71234           ffffff
2   http://www.transitchicago.com/bus/3/      99999C           ffffff
3   http://www.transitchicago.com/bus/4/      414145           ffffff
4  http://www.transitchicago.com/bus/X4/      b71234           ffffff

In [10]:
stops.head()

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,location_type,parent_station,wheelchair_boarding
0,1,1.0,Jackson & Austin Terminal,"Jackson & Austin Terminal, Northeastbound, Bus...",41.876330,-87.774111,0,NaN,1
1,2,2.0,5900 W Jackson,"5900 W Jackson, Eastbound, Southside of the St...",41.877075,-87.771324,0,NaN,1
2,4,4.0,5700 W Jackson,"5700 W Jackson, Eastbound, Southside of the St...",41.876992,-87.768264,0,NaN,1
3,6,6.0,Jackson & Lotus,"Jackson & Lotus, Eastbound, Southeast Corner",41.876521,-87.761452,0,NaN,1
4,7,7.0,5351 W Jackson,"5351 W Jackson, Eastbound, Southside of the St...",41.876560,-87.758931,0,NaN,1

In [12]:
specific_routes = routes[(routes["route_short_name"] == "4")]
specific_routes

,agency_id,route_id,route_short_name,route_long_name,route_type,route_url,route_color,route_text_color
3,50066,4,4,Cottage Grove,3,http://www.transitchicago.com/bus/4/,414145,ffffff

In [42]:
specific_trips = trips[trips["route_id"] == "4"]
print(specific_trips)
print(specific_trips.describe())
print(specific_trips.service_id.unique())
#print(specific_trips.service_id.value_counts()) 
#just use 679 as it is the newest. However, it doesn't really matter.
#mainly look at 67801, 67806, and 67809. 67801 is best.
specific_trips = trips[(trips["route_id"] == "4") & (trips["service_id"] == 67801)]
print(specific_trips)

      route_id  service_id        trip_id  direction_id      block_id  \
29341        4       67801  6780000064020             0  678000002694
29342        4       67801  6780000535020             0  678000004297
29343        4       67801  6780000638020             0  678000002643
29344        4       67801  6780001034020             0  678000002693
29345        4       67801  6780002484020             0  678000002645
...        ...         ...            ...           ...           ...
30802        4       67915  6790002347010             1  679000004152
30803        4       67915  6790015535010             1  679000004146
30804        4       67915  6790025912010             1  679000004139
30805        4       67915  6790028937010             1  679000004145
30806        4       67915  6790030085010             1  679000004153

       shape_id direction  wheelchair_accessible  schd_trip_id
29341  67819379     South                      1         64020
29342  67819379     South                      1        535020
29343  67819379     South                      1        638020
29344  67819379     South                      1       1034020
29345  67819379     South                      1       2484020
...         ...       ...                    ...           ...
30802  67928326     North                      1       2347010
30803  67928326     North                      1      15535010
30804  67928326     North                      1      25912010
30805  67928326     North                      1      28937010
30806  67928326     North                      1      30085010

[1466 rows x 9 columns]
         service_id       trip_id  direction_id      block_id      shape_id  \
count   1466.000000  1.466000e+03   1466.000000  1.466000e+03  1.466000e+03
mean   67855.413370  6.785009e+12      0.502046  6.784986e+11  6.787031e+07
std       50.147492  5.001707e+09      0.500166  5.001687e+08  5.010803e+04
min    67801.000000  6.780000e+12      0.000000  6.780000e+11  6.780813e+07
25%    67806.000000  6.780021e+12      0.000000  6.780000e+11  6.781938e+07
50%    67815.000000  6.780050e+12      1.000000  6.780000e+11  6.782833e+07
75%    67906.000000  6.790022e+12      1.000000  6.790000e+11  6.791938e+07
max    67915.000000  6.790050e+12      1.000000  6.790000e+11  6.792833e+07

       wheelchair_accessible  schd_trip_id
count                 1466.0  1.466000e+03
mean                     1.0  2.264129e+07
std                      0.0  1.445089e+07
min                      1.0  6.070000e+03
25%                      1.0  1.007378e+07
50%                      1.0  2.139354e+07
75%                      1.0  3.451378e+07
max                      1.0  5.037101e+07
[67801 67802 67805 67806 67808 67809 67812 67815 67901 67906 67908 67909
 67912 67915]
      route_id  service_id        trip_id  direction_id      block_id  \
29341        4       67801  6780000064020             0  678000002694
29342        4       67801  6780000535020             0  678000004297
29343        4       67801  6780000638020             0  678000002643
29344        4       67801  6780001034020             0  678000002693
29345        4       67801  6780002484020             0  678000002645
...        ...         ...            ...           ...           ...
29572        4       67801  6780048813020             1  678000002645
29573        4       67801  6780049011020             1  678000002647
29574        4       67801  6780049819020             1  678000002693
29575        4       67801  6780049996020             1  678000002619
29576        4       67801  6780050093020             1  678000002645

       shape_id direction  wheelchair_accessible  schd_trip_id
29341  67819379     South                      1         64020
29342  67819379     South                      1        535020
29343  67819379     South                      1        638020
29344  67819379     South                      1       1034020
29345  67819379     South                      1       2484020
...         ...       ...                    ...           ...
29572  67819378     North                      1      48813020
29573  67819378     North                      1      49011020
29574  67819378     North                      1      49819020
29575  67819378     North                      1      49996020
29576  67819378     North                      1      50093020

[236 rows x 9 columns]

In [43]:
filtered_stoptimes = stop_times[stop_times["trip_id"] == 6780000535020]
filtered_stoptimes

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,shape_dist_traveled
196372,6780000535020,19:01:30,19:01:30,2530,1,115th,0,0
196373,6780000535020,19:02:49,19:02:49,14222,2,115th,0,1254
196374,6780000535020,19:03:42,19:03:42,14224,3,115th,0,1756
196375,6780000535020,19:05:29,19:05:29,1104,4,115th,0,2599
196376,6780000535020,19:06:33,19:06:33,1105,5,115th,0,3347
...,...,...,...,...,...,...,...,...
196489,6780000535020,20:22:57,20:22:57,2838,118,115th,0,78297
196490,6780000535020,20:23:39,20:23:39,15156,119,115th,0,79024
196491,6780000535020,20:24:21,20:24:21,2840,120,115th,0,79605
196492,6780000535020,20:24:53,20:24:53,2841,121,115th,0,80190
196493,6780000535020,20:25:30,20:25:30,18241,122,115th,0,80619

In [17]:
filtered_stops = filtered_stoptimes.merge(stops[['stop_id', 'stop_name', 'stop_lat', 'stop_lon']], on='stop_id', how='left')
filtered_stops

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,shape_dist_traveled,stop_name,stop_lat,stop_lon
0,6780000064020,14:13:00,14:13:00,2530,1,115th,0,0,Columbus & Randolph,41.884788,-87.620519
1,6780000064020,14:14:30,14:14:30,14222,2,115th,0,1254,Wacker (Upper) & Columbus,41.888098,-87.620850
2,6780000064020,14:15:31,14:15:31,14224,3,115th,0,1756,Wacker (Upper) & Stetson,41.888335,-87.622860
3,6780000064020,14:17:32,14:17:32,1104,4,115th,0,2599,Michigan & South Water,41.886912,-87.624686
4,6780000064020,14:18:45,14:18:45,1105,5,115th,0,3347,Michigan & Lake/Randolph,41.885112,-87.624621
...,...,...,...,...,...,...,...,...,...,...,...
117,6780000064020,15:47:07,15:47:07,2838,118,115th,0,78297,Cottage Grove & 112th Street,41.691081,-87.610380
118,6780000064020,15:47:54,15:47:54,15156,119,115th,0,79024,Cottage Grove & 113th Street,41.688992,-87.610805
119,6780000064020,15:48:42,15:48:42,2840,120,115th,0,79605,Cottage Grove & 114th Street,41.687457,-87.611197
120,6780000064020,15:49:18,15:49:18,2841,121,115th,0,80190,Cottage Grove & 115th Street,41.685596,-87.611506
121,6780000064020,15:50:00,15:50:00,18241,122,115th,0,80619,115th Street Metra Station,41.685605,-87.612332

In [34]:
#the service id is equal to the days of the week in binary lol
#67801 = regular weekdays
#67802 = first 4 weekdays
#67805 = Friday
#67806 = Saturday
#67808,67809 = Sunday
#67812 = Tuesday - Saturday
#67815 = Monday
#67901 = Weekdays (new?)
#678xx - May 28 to June 6, 679xx = June 7 to July 31

#319 = Weekdays + Saturday
#288 = Saturday
#448 = Sunday
#Combinations: 287, 288, 448 or 319, 448
calendar[calendar.service_id == 67912]
print(calendar[calendar.service_id == 67912])

    service_id  monday  tuesday  wednesday  thursday  friday  saturday  \
53       67912       0        1          1         1       1         1

    sunday  start_date  end_date
53       0    20260607  20260731

In [46]:
frequencies[frequencies.trip_id == '2002580-2-287-1000']

                  trip_id start_time  end_time  headway_secs
43503  2002580-2-287-1000   10:00:00  16:00:00           480

In [47]:
shapes

,shape_id,shape_pt_lat,shape_pt_lon,shape_pt_sequence,shape_dist_traveled
0,67800095,41.911304,-87.631222,1,0
1,67800095,41.911304,-87.631222,2,49
2,67800095,41.911180,-87.631290,3,106
3,67800095,41.911180,-87.631500,4,157
4,67800095,41.911180,-87.631690,5,224
...,...,...,...,...,...
1331487,309100138,42.020363,-87.674744,129,25341
1331488,309100138,42.020213,-87.674492,130,25428
1331489,309100138,42.019871,-87.673888,131,25634
1331490,309100138,42.019518,-87.673454,132,25809
1331491,309100138,42.019071,-87.672898,133,26031

In [56]:
specific_trips[(specific_trips["service_id"] == 67901) & (specific_trips["direction_id"] == 0)].shape_id.unique()

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().