In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
routes = pd.read_csv("../hk_gtfs/routes.txt")

trips = pd.read_csv("../hk_gtfs/trips.txt")

In [4]:
stop_times = pd.read_csv("../hk_gtfs/stop_times.txt")

In [5]:
stops = pd.read_csv("../hk_gtfs/stops.txt")

In [23]:
routes.head()

,route_id,agency_id,route_short_name,route_long_name,route_type,route_url
0,1001,KMB,1,CHUK YUEN ESTATE - STAR FERRY,3,https://search.kmb.hk/KMBWebSite/?action=route...
1,1002,KMB,10,CHOI WAN - TAI KOK TSUI (CIRCULAR),3,https://search.kmb.hk/KMBWebSite/?action=route...
2,1006,KMB+CTB,102P,SHAU KEI WAN - MEI FOO,3,https://search.kmb.hk/KMBWebSite/?action=route...
3,1008,KMB+CTB,103,CHUK YUEN ESTATE - POKFIELD RD,3,https://search.kmb.hk/KMBWebSite/?action=route...
4,1010,KMB+CTB,106,WONG TAI SIN - SIU SAI WAN (ISLAND RESORT),3,https://search.kmb.hk/KMBWebSite/?action=route...

In [10]:
stops.head()

,stop_id,stop_name,stop_lat,stop_lon,zone_id,location_type,stop_timezone
0,2,"[CTB] HIU TSUI STREET, SIU SAI WAN ROAD|[KMB+C...",22.26436,114.24821,2,0,Asia/Hong_Kong
1,3,"[CTB] FU SHING COURT, CHAI WAN ROAD|[KMB+CTB] ...",22.26578,114.24542,3,0,Asia/Hong_Kong
2,4,"[CTB] LOK HIN TERRACE, CHAI WAN ROAD|[KMB+CTB]...",22.26492,114.24167,4,0,Asia/Hong_Kong
3,5,"[CTB] WAN TSUI SHOPPING CENTRE, CHAI WAN ROAD|...",22.26312,114.23875,5,0,Asia/Hong_Kong
4,6,"[CTB] CHAK TSUI HOUSE WAN TSUI ESTATE, WAN TSU...",22.26242,114.23655,6,0,Asia/Hong_Kong

In [45]:
specific_routes = routes[(routes["route_short_name"] == "10") & (routes["agency_id"] != "NLB")]
specific_routes

,route_id,agency_id,route_short_name,route_long_name,route_type,route_url
1,1002,KMB,10,CHOI WAN - TAI KOK TSUI (CIRCULAR),3,https://search.kmb.hk/KMBWebSite/?action=route...
1302,1000295,CTB,10,KENNEDY TOWN - NORTH POINT FERRY PIER (OMIT CH...,3,https://mobile.citybus.com.hk/nwp3/?f=1&ds=10&...
1303,1000296,CTB,10,NORTH POINT FERRY PIER - KENNEDY TOWN,3,https://mobile.citybus.com.hk/nwp3/?f=1&ds=10&...
2102,2006706,GMB,10,CAUSEWAY BAY (JAFFE ROAD) - CYBERPORT PUBLIC T...,3,https://h2-app-rr.hkemobility.gov.hk/ris_page/...

In [46]:
specific_trips = trips[trips["route_id"] == 2006706]
specific_trips

       route_id  service_id             trip_id
39297   2006706         480  2006706-2-480-1840
39298   2006706         480  2006706-2-480-0840
39299   2006706         287  2006706-2-287-1900
39300   2006706         287  2006706-2-287-1700
39301   2006706         287  2006706-2-287-0840
39302   2006706         287  2006706-2-287-0740
39303   2006706         287  2006706-2-287-0700
57411   2006706         480  2006706-1-480-1800
57412   2006706         480  2006706-1-480-0800
57413   2006706         287  2006706-1-287-1850
57414   2006706         287  2006706-1-287-1835
57415   2006706         287  2006706-1-287-1815
57416   2006706         287  2006706-1-287-1400
57417   2006706         287  2006706-1-287-0840
57418   2006706         287  2006706-1-287-0725
57419   2006706         287  2006706-1-287-0715
57420   2006706         287  2006706-1-287-0700
57421   2006706         287  2006706-1-287-0650
57422   2006706         287  2006706-1-287-0635
57423   2006706         287  2006706-1-287-0625

In [47]:
filtered_stoptimes = stop_times[stop_times["trip_id"] == "2006706-2-480-1840"]
filtered_stoptimes

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,timepoint
1117138,2006706-2-480-1840,18:40:00,18:40:00,20014874,1,0,1,1
1117139,2006706-2-480-1840,NaN,NaN,20014875,2,0,0,0
1117140,2006706-2-480-1840,NaN,NaN,20000331,3,0,0,0
1117141,2006706-2-480-1840,NaN,NaN,20000011,4,0,0,0
1117142,2006706-2-480-1840,NaN,NaN,20014876,5,0,0,0
1117143,2006706-2-480-1840,NaN,NaN,20002403,6,0,0,0
1117144,2006706-2-480-1840,NaN,NaN,20000174,7,0,0,0
1117145,2006706-2-480-1840,NaN,NaN,20014877,8,0,0,0
1117146,2006706-2-480-1840,NaN,NaN,20014878,9,0,0,0
1117147,2006706-2-480-1840,NaN,NaN,20014879,10,0,0,0
1117148,2006706-2-480-1840,NaN,NaN,20014880,11,0,0,0
1117149,2006706-2-480-1840,NaN,NaN,20000015,12,0,0,0
1117150,2006706-2-480-1840,NaN,NaN,20014527,13,0,0,0
1117151,2006706-2-480-1840,NaN,NaN,20014881,14,0,0,0
1117152,2006706-2-480-1840,NaN,NaN,20014537,15,0,0,0
1117153,2006706-2-480-1840,NaN,NaN,20000017,16,0,0,0
1117154,2006706-2-480-1840,NaN,NaN,20000018,17,0,0,0
1117155,2006706-2-480-1840,NaN,NaN,20000019,18,0,0,0
1117156,2006706-2-480-1840,NaN,NaN,20000020,19,0,0,0
1117157,2006706-2-480-1840,NaN,NaN,20014882,20,0,0,0
1117158,2006706-2-480-1840,NaN,NaN,20014883,21,0,0,0
1117159,2006706-2-480-1840,NaN,NaN,20014884,22,0,0,0
1117160,2006706-2-480-1840,19:12:00,19:12:00,20014859,23,1,0,1

In [48]:
filtered_stops = filtered_stoptimes.merge(stops[['stop_id', 'stop_name', 'stop_lat', 'stop_lon']], on='stop_id', how='left')
filtered_stops

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,timepoint,stop_name,stop_lat,stop_lon
0,2006706-2-480-1840,18:40:00,18:40:00,20014874,1,0,1,1,CYBERPORT BUS TERMINUS,22.26238,114.13007
1,2006706-2-480-1840,NaN,NaN,20014875,2,0,0,0,"SHA WAN DRIVE, NEAR UNIVERSITY OF HONG KONG ST...",22.26676,114.12603
2,2006706-2-480-1840,NaN,NaN,20000331,3,0,0,0,"SHA WAN DRIVE, OPPOSITE MACLEHOSE MEDICAL REHA...",22.26980,114.12374
3,2006706-2-480-1840,NaN,NaN,20000011,4,0,0,0,SANDY BAY ROAD,22.27168,114.12468
4,2006706-2-480-1840,NaN,NaN,20014876,5,0,0,0,"CONSORT RISE, NEAR CONSORT VILLAS HOUSE A",22.27025,114.12752
5,2006706-2-480-1840,NaN,NaN,20002403,6,0,0,0,"MOUNT DAVIS ROAD, POK FU LAM ROAD",22.27764,114.13065
6,2006706-2-480-1840,NaN,NaN,20000174,7,0,0,0,"POK FU LAM ROAD, POK FIELD ROAD",22.28177,114.13204
7,2006706-2-480-1840,NaN,NaN,20014877,8,0,0,0,"POK FU LAM ROAD, NEAR LADY HO TUNG HALL, THE U...",22.28413,114.13352
8,2006706-2-480-1840,NaN,NaN,20014878,9,0,0,0,"POK FU LAM ROAD, NEAR THE BELCHER'S TOWER 3",22.28442,114.13424
9,2006706-2-480-1840,NaN,NaN,20014879,10,0,0,0,"BONHAM ROAD, NEAR SAINT STEPHEN'S CHURCH & KIN...",22.28475,114.13826
10,2006706-2-480-1840,NaN,NaN,20014880,11,0,0,0,"BONHAM ROAD, NEAR ST PAUL'S COLLEGE",22.28395,114.13872
11,2006706-2-480-1840,NaN,NaN,20000015,12,0,0,0,"BONHAM ROAD, HOUSE NO. 53",22.28486,114.14120
12,2006706-2-480-1840,NaN,NaN,20014527,13,0,0,0,"BONHAM ROAD, NEAR SAI YING PUN STATION EXIT C|...",22.28438,114.14345
13,2006706-2-480-1840,NaN,NaN,20014881,14,0,0,0,"BONHAM ROAD, PARKWAY COURT",22.28472,114.14591
14,2006706-2-480-1840,NaN,NaN,20014537,15,0,0,0,"BONHAM ROAD, HOSPITAL ROAD|BONHAM ROAD NEAR HO...",22.28363,114.14747
15,2006706-2-480-1840,NaN,NaN,20000017,16,0,0,0,"CAINE ROAD, LADDER STREET|CAINE ROAD, NEAR LAD...",22.28315,114.14881
16,2006706-2-480-1840,NaN,NaN,20000018,17,0,0,0,"CAINE ROAD, SHING WONG STREET|CAINE ROAD, NEAR...",22.28282,114.15025
17,2006706-2-480-1840,NaN,NaN,20000019,18,0,0,0,"79 CAINE ROAD, NEAR PEEL STREET|CAINE ROAD, PE...",22.28167,114.15167
18,2006706-2-480-1840,NaN,NaN,20000020,19,0,0,0,"QUEENSWAY, NEAR ADMIRALTY STATION EXIT C1|QUEE...",22.27846,114.16468
19,2006706-2-480-1840,NaN,NaN,20014882,20,0,0,0,"HENNESSY ROAD, NEAR ONE HENNESSY",22.27786,114.16900
20,2006706-2-480-1840,NaN,NaN,20014883,21,0,0,0,"HENNESSY ROAD, NEAR FRIENDSHIP MANSION",22.27868,114.17893
21,2006706-2-480-1840,NaN,NaN,20014884,22,0,0,0,"LOCKHART ROAD, NEAR CAUSEWAY BAY PLAZA 2",22.28043,114.18221
22,2006706-2-480-1840,19:12:00,19:12:00,20014859,23,1,0,1,"JAFFE ROAD, NEAR SIU ON PLAZA|JAFFE ROAD, NEAR...",22.28094,114.18247