In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
routes = pd.read_csv("../hk_gtfs/routes.txt")

In [25]:
trips = pd.read_csv("../hk_gtfs/trips.txt")

In [26]:
stop_times = pd.read_csv("../hk_gtfs/stop_times.txt")

In [27]:
stops = pd.read_csv("../hk_gtfs/stops.txt")

In [28]:
calendar = pd.read_csv("../hk_gtfs/calendar.txt")
calendar_dates = pd.read_csv("../hk_gtfs/calendar_dates.txt")

In [29]:
frequencies = pd.read_csv("../hk_gtfs/frequencies.txt")

In [18]:
routes.head()

,route_id,agency_id,route_short_name,route_long_name,route_type,route_url
0,1001,KMB,1,CHUK YUEN ESTATE - STAR FERRY,3,https://search.kmb.hk/KMBWebSite/?action=route...
1,1002,KMB,10,CHOI WAN - TAI KOK TSUI (CIRCULAR),3,https://search.kmb.hk/KMBWebSite/?action=route...
2,1006,KMB+CTB,102P,SHAU KEI WAN - MEI FOO,3,https://search.kmb.hk/KMBWebSite/?action=route...
3,1008,KMB+CTB,103,CHUK YUEN ESTATE - POKFIELD RD,3,https://search.kmb.hk/KMBWebSite/?action=route...
4,1010,KMB+CTB,106,WONG TAI SIN - SIU SAI WAN (ISLAND RESORT),3,https://search.kmb.hk/KMBWebSite/?action=route...

In [19]:
stops.head()

,stop_id,stop_name,stop_lat,stop_lon,zone_id,location_type,stop_timezone
0,2,"[CTB] HIU TSUI STREET, SIU SAI WAN ROAD|[KMB+C...",22.26436,114.24821,2,0,Asia/Hong_Kong
1,3,"[CTB] FU SHING COURT, CHAI WAN ROAD|[KMB+CTB] ...",22.26578,114.24542,3,0,Asia/Hong_Kong
2,4,"[CTB] LOK HIN TERRACE, CHAI WAN ROAD|[KMB+CTB]...",22.26492,114.24167,4,0,Asia/Hong_Kong
3,5,"[CTB] WAN TSUI SHOPPING CENTRE, CHAI WAN ROAD|...",22.26312,114.23875,5,0,Asia/Hong_Kong
4,6,"[CTB] CHAK TSUI HOUSE WAN TSUI ESTATE, WAN TSU...",22.26242,114.23655,6,0,Asia/Hong_Kong

In [52]:
specific_routes = routes[(routes["route_short_name"] == "58") & (routes["agency_id"] != "NLB")]
specific_routes

,route_id,agency_id,route_short_name,route_long_name,route_type,route_url
1787,2002580,GMB,58,ABERDEEN (WU NAM STREET) - KENNEDY TOWN STATION,3,https://h2-app-rr.hkemobility.gov.hk/ris_page/...
1818,2002646,GMB,58,SHA WAN DRIVE - KENNEDY TOWN STATION (SPECIAL...,3,https://h2-app-rr.hkemobility.gov.hk/ris_page/...
1819,2002679,GMB,58,SANDY BAY ROAD - ABERDEEN (SPECIAL DEPARTURES),3,https://h2-app-rr.hkemobility.gov.hk/ris_page/...

In [54]:
specific_trips = trips[trips["route_id"] == 2002580]
specific_trips

       route_id  service_id             trip_id
61921   2002580         448  2002580-1-448-2330
61922   2002580         448  2002580-1-448-1900
61923   2002580         448  2002580-1-448-1600
61924   2002580         448  2002580-1-448-1000
61925   2002580         448  2002580-1-448-0600
61926   2002580         448  2002580-1-448-0530
61927   2002580         288  2002580-1-288-2330
61928   2002580         288  2002580-1-288-1900
61929   2002580         288  2002580-1-288-1600
61930   2002580         288  2002580-1-288-1000
61931   2002580         288  2002580-1-288-0700
61932   2002580         288  2002580-1-288-0600
61933   2002580         288  2002580-1-288-0530
61934   2002580         287  2002580-1-287-2330
61935   2002580         287  2002580-1-287-1900
61936   2002580         287  2002580-1-287-1600
61937   2002580         287  2002580-1-287-1000
61938   2002580         287  2002580-1-287-0700
61939   2002580         287  2002580-1-287-0600
61940   2002580         287  2002580-1-287-0530
72114   2002580         448  2002580-2-448-2330
72115   2002580         448  2002580-2-448-1900
72116   2002580         448  2002580-2-448-1600
72117   2002580         448  2002580-2-448-1000
72118   2002580         448  2002580-2-448-0600
72119   2002580         448  2002580-2-448-0530
72120   2002580         288  2002580-2-288-2330
72121   2002580         288  2002580-2-288-1900
72122   2002580         288  2002580-2-288-1600
72123   2002580         288  2002580-2-288-1000
72124   2002580         288  2002580-2-288-0700
72125   2002580         288  2002580-2-288-0600
72126   2002580         288  2002580-2-288-0530
72127   2002580         287  2002580-2-287-2330
72128   2002580         287  2002580-2-287-1900
72129   2002580         287  2002580-2-287-1600
72130   2002580         287  2002580-2-287-1000
72131   2002580         287  2002580-2-287-0700
72132   2002580         287  2002580-2-287-0600
72133   2002580         287  2002580-2-287-0530

In [57]:
filtered_stoptimes = stop_times[stop_times["trip_id"] == "2002580-2-287-1000"]
filtered_stoptimes

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,timepoint
958053,2002580-2-287-1000,10:00:00,10:00:00,20009733,1,0,1,1
958054,2002580-2-287-1000,NaN,NaN,20000334,2,0,0,0
958055,2002580-2-287-1000,NaN,NaN,20009766,3,0,0,0
958056,2002580-2-287-1000,NaN,NaN,20004594,4,0,0,0
958057,2002580-2-287-1000,NaN,NaN,20009736,5,0,0,0
958058,2002580-2-287-1000,NaN,NaN,20007719,6,0,0,0
958059,2002580-2-287-1000,NaN,NaN,20002491,7,0,0,0
958060,2002580-2-287-1000,NaN,NaN,20002492,8,0,0,0
958061,2002580-2-287-1000,NaN,NaN,20004115,9,0,0,0
958062,2002580-2-287-1000,NaN,NaN,20000370,10,0,0,0
958063,2002580-2-287-1000,10:20:00,10:20:00,20000326,11,1,0,1

In [58]:
filtered_stops = filtered_stoptimes.merge(stops[['stop_id', 'stop_name', 'stop_lat', 'stop_lon']], on='stop_id', how='left')
filtered_stops

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,timepoint,stop_name,stop_lat,stop_lon
0,2002580-2-287-1000,10:00:00,10:00:00,20009733,1,0,1,1,KENNEDY TOWN STATION,22.28135,114.12893
1,2002580-2-287-1000,NaN,NaN,20000334,2,0,0,0,"VICTORIA ROAD, OPPOSITE ENGLISH SCHOOLS FOUNDA...",22.27322,114.12643
2,2002580-2-287-1000,NaN,NaN,20009766,3,0,0,0,"FUNG YIU KING HOSPITAL, SANDY BAY ROAD|SANDY B...",22.27186,114.12502
3,2002580-2-287-1000,NaN,NaN,20004594,4,0,0,0,"SHA WAN DRIVE, OUTSIDE MACLEHOSE MEDICAL REHAB...",22.26978,114.12387
4,2002580-2-287-1000,NaN,NaN,20009736,5,0,0,0,THE LAYBY AT CYBERPORT ROAD OPPOSITE TO THE AR...,22.26147,114.13023
5,2002580-2-287-1000,NaN,NaN,20007719,6,0,0,0,"INFORMATION CRESCENT, CYBERPORT ROAD",22.26095,114.13142
6,2002580-2-287-1000,NaN,NaN,20002491,7,0,0,0,"CYBERPORT ROAD, OPPOSITE CYBERPORT 3|CYBERPORT...",22.25985,114.13254
7,2002580-2-287-1000,NaN,NaN,20002492,8,0,0,0,"BEL-AIR PHASE 2, CYPERPORT ROAD|CYPERPORT ROAD...",22.25667,114.13279
8,2002580-2-287-1000,NaN,NaN,20004115,9,0,0,0,"BEL-AIR ON THE PEAK, CYBERPORT ROAD|BEL-AIR ON...",22.25473,114.13364
9,2002580-2-287-1000,NaN,NaN,20000370,10,0,0,0,"SHEK PAI WAN ROAD, NEAR TIN WAN STREET|SHEK PA...",22.24935,114.14855
10,2002580-2-287-1000,10:20:00,10:20:00,20000326,11,1,0,1,"WU NAM STREET, OUTSIDE ON TAI BUILDING",22.24775,114.15558

In [64]:
#the service id is equal to the days of the week in binary lol
calendar[calendar.service_id == 287]

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
286,287,1,1,1,1,1,0,0,20200101,20991231

In [59]:
frequencies[frequencies.trip_id == '2002580-2-287-1000']

                  trip_id start_time  end_time  headway_secs
43503  2002580-2-287-1000   10:00:00  16:00:00           480